Repository imskr/Plant_Disease_Detection, pull requests merged in 2020-03, with the labels that each got.

#18 Updated README
  README.md
Labels: beginner, gssoc20

#10 #9 gs so c
  README.md
Labels: beginner, gssoc20

#22 feat: Update README.md
  README.md
Labels: beginner, gssoc20

#25 Updated README.md to remove configuration section
  README.md
Labels: beginner, gssoc20

#26 Update README with Docker setup on Mac
  README.md
Labels: beginner, gssoc20

#33 update readme.md with Docker steps on Windows
  README.md
Labels: beginner, gssoc20

#34 New UI
  css/style.css
  images/bgd.jpg
  images/img.jpg
  images/leaf.png
  index.html
  js/main.js
Labels: gssoc20, hard

#37 Keras implementation
  .dockerignore
  .github/FUNDING.yml
  .gitignore
  Dockerfile
  LICENSE
  app.yaml
  app/models/models.md
  app/server.py
  app/static/client.js
  app/static/style.css
  app/view/index.html
  notebook/Plant_Disease_Detection_Keras.ipynb
  notebook/plant_disease_detector.ipynb
  requirements.txt
Labels: gssoc20, hard

#42 Added issue template
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: easy, gssoc20

#43 Add Directory "deployment_guide"
  .dockerignore
  Dockerfile
  app.yaml
  app/server.py
  deployment_guide/gcp_deployment.md
  deployment_guide/images/gcp-console-example.png
  deployment_guide/images/gcp-create-project.png
  deployment_guide/images/gcp-open-console.png
Labels: gssoc20, medium

#46 Updated README.MD and Created CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: gssoc20, medium

#44 Added the GDP deployment guideline
  README.md
Labels: easy, gssoc20

#48 NEW UI
  README.md
  app/static/SS.png
  app/static/background.jpg
  app/static/bgd.jpg
  app/static/client.js
  app/static/img.jpg
  app/static/img1.png
  app/static/leaf.png
  app/static/style.css
  app/view/index.html
Labels: enhancement, gssoc20, hard

#50 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: easy, gssoc20
