Repository imskr/Plant_Disease_Detection, pull requests merged in 2020-04, with the labels that each got.

#51 Update README with Docker setup on Linux #16
  README.md
Labels: beginner, gssoc20

#52 Gretings.yml
  .github/workflows/greetings.yml
Labels: gssoc20, medium

#61 Automatically assign code owners review
  .github/CODEOWNERS
Labels: easy, gssoc20

#63 PR template not working as expected
  .github/pull_request_template.md
Labels: beginner, gssoc20

#69 Add Deployment on AWS Elasticbeans - resolved
  README.md
  deployment_guide/aws_deployment.md
  deployment_guide/images/aws-app-init.png
  deployment_guide/images/aws-deployed-banner.png
Labels: gssoc20, hard

#73 Updated local setup instructions (without Docker)
  README.md
Labels: gssoc20, medium

#75 ResNet34 using fastai implementation
  notebook/Plant_Disease_Detection_Fastai.ipynb
Labels: gssoc20, hard

#76 Deploy the model locally without docker
  deployment_guide/local_flask/README.md
  deployment_guide/local_flask/requirements.txt
  deployment_guide/local_flask/static/bgd.jpg
  deployment_guide/local_flask/static/client.js
  deployment_guide/local_flask/static/img.jpg
  deployment_guide/local_flask/static/leaf.png
  deployment_guide/local_flask/static/style.css
  deployment_guide/local_flask/templates/index.html
  deployment_guide/local_flask/webapp.py
Labels: gssoc20, hard
